src/Entity/Cave.php
<?php

namespace App\Entity;

use App\Repository\CaveRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CaveRepository::class)]
class Cave
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity:"App\Entity\Utilisateur", inversedBy: 'cave')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Utilisateur $utilistaeur_id = null;

    #[ORM\ManyToOne(targetEntity:"App\Entity\Vin", inversedBy: 'cave')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Vin $id_vin = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $enter_date = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE, nullable: true)]
    private ?\DateTimeImmutable $exit_date = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUtilistaeurId(): ?Utilisateur
    {
        return $this->utilistaeur_id;
    }

    public function setUtilistaeurId(?Utilisateur $utilistaeur_id): self
    {
        $this->utilistaeur_id = $utilistaeur_id;

        return $this;
    }

    public function getIdVin(): ?Vin
    {
        return $this->id_vin;
    }

    public function setIdVin(Vin $id_vin): self
    {
        $this->id_vin = $id_vin;

        return $this;
    }

    public function getEnterDate(): ?\DateTimeImmutable
    {
        return $this->enter_date;
    }

    public function setEnterDate(\DateTimeImmutable $enter_date): self
    {
        $this->enter_date = $enter_date;

        return $this;
    }

    public function getExitDate(): ?\DateTimeImmutable
    {
        return $this->exit_date;
    }

    public function setExitDate(?\DateTimeImmutable $exit_date): self
    {
        $this->exit_date = $exit_date;

        return $this;
    }
}

src/Entity/Vin.php
<?php

namespace App\Entity;

use App\Repository\VinRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\component\HttpFoundation\File\File;


#[ORM\Entity(repositoryClass: VinRepository::class)]
class Vin
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $Annee = null;

    #[ORM\Column]
    private ?int $formatCl = null;

    #[ORM\ManyToOne(inversedBy: 'Robe')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Robe $robe = null;

    #[ORM\ManyToOne(inversedBy: 'vins')]
    #[ORM\JoinColumn(nullable: false)]
    private ?TeneurEnSucre $TeneurEnSucre = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getAnnee(): ?string
    {
        if ($this->Annee === null) {
            return null;
        }
        
        return $this->Annee->format('Y');       
    }

    public function setAnnee(?int $Annee): self
    {
        $this->Annee = \DateTimeImmutable::createFromFormat('Y', (string)$Annee);
        return $this;
    }

    public function getFormatCl(): ?string
    {
        return (string)$this->formatCl;
    }

    public function setFormatCl(int $formatCl): self
    {
        $this->formatCl = $formatCl;

        return $this;
    }

    public function getRobe(): ?Robe
    {
        return $this->robe;
    }

    public function setRobe(?Robe $robe): self
    {
        $this->robe = $robe;

        return $this;
    }

    public function getTeneurEnSucre(): ?TeneurEnSucre
    {
        return $this->TeneurEnSucre;
    }

    public function setTeneurEnSucre(?TeneurEnSucre $TeneurEnSucre): self
    {
        $this->TeneurEnSucre = $TeneurEnSucre;

        return $this;
    }

    public function __toString()
    {
        return $this->Nom . " " . $this->Annee->format('Y'); 
    }
}

src/Form/CaveType.php
<?php

namespace App\Form;

use App\Entity\Utilisateur;
use App\Entity\Cave;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Security\Core\Security;

use Karser\Recaptcha3Bundle\Form\Recaptcha3Type;
use Karser\Recaptcha3Bundle\Validator\Constraints\Recaptcha3;

class CaveType extends AbstractType
{
    private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $user = $this->security->getUser();
        $builder
            ->add('enter_date', null, [
                'label' => 'Date d\'entrée',
            ])
            ->add('exit_date', null, [
                'label' => 'Date de sortie',
            ])
            ->add('utilistaeur_id', EntityType::class, [
                'class' => Utilisateur::class,
                'data' => $user,
            ])
            ->add('id_vin', null, [
                'label' => 'Vin',
            ])
            ->add('captcha', Recaptcha3Type::class, [
                'constraints' => new Recaptcha3(),
                'action_name' => 'app_cave_new',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Cave::class,
        ]);
    }
}

src/Controller/CaveController.php
<?php

namespace App\Controller;
use App\Entity\Utilisateur;

use App\Entity\Cave;
use App\Form\CaveType;
use App\Repository\CaveRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;

#[Route('/cave')]
class CaveController extends AbstractController
{
    #[Route('/', name: 'app_cave_index', methods: ['GET'])]
    public function index(CaveRepository $caveRepository, UserInterface $user): Response
    {
        $userId = $user->getId();
        $userRemplissage = $caveRepository->getRemplissage($userId);
        
        return $this->render('cave/index.html.twig', [
            'caves' => $caveRepository->findAllWhitNameWine($userId),
            'remplissage' => (int)$userRemplissage
        ]);
    }

    #[Route('/new', name: 'app_cave_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CaveRepository $caveRepository, UserInterface $user): Response
    {
        $cave = new Cave();
        $form = $this->createForm(CaveType::class, $cave);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid() && $cave->getUtilistaeurId() === $user) {
            $caveRepository->save($cave, true);

            return $this->redirectToRoute('app_cave_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('cave/new.html.twig', [
            'cave' => $cave,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_cave_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Cave $cave, CaveRepository $caveRepository, UserInterface $user): Response
    {
        // Vérifier si l'utilisateur associé à la cave correspond à l'utilisateur actuel
        if ($cave->getUtilistaeurId() !== $user) {
            // Rediriger l'utilisateur vers une autre page
            return $this->redirectToRoute('app_cave_index');
        }
        $form = $this->createForm(CaveType::class, $cave);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $caveRepository->save($cave, true);

            return $this->redirectToRoute('app_cave_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('cave/edit.html.twig', [
            'cave' => $cave,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_cave_delete', methods: ['POST'])]
    public function delete(Request $request, Cave $cave, CaveRepository $caveRepository, UserInterface $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$cave->getId(), $request->request->get('_token')) && $cave->getUtilistaeurId() === $user) {
            $caveRepository->remove($cave, true);
        }

        return $this->redirectToRoute('app_cave_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/cave/_delete_form.html.twig
<form  class="col-12 text-center" method="post" action="{{ path('app_cave_delete', {'id': cave.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ cave.id) }}">
    <button class="btn btn-primary">Delete</button>
</form>

templates/cave/_form.html.twig
{{ form_start(form) }}
    {{ form_row(form.enter_date, {'attr': {'style': 'color: white;', 'class': 'form-control'}, 'label_attr': {'style': 'color: white;'}}) }}
    {{ form_row(form.exit_date, {'attr': {'style': 'color: white;', 'class': 'form-control'}, 'label_attr': {'style': 'color: white;'}}) }}
    {{ form_row(form.utilistaeur_id, {'attr': {'style': 'display: none;'}, 'label_attr': {'style': 'display: none;'}}) }}
    {{ form_row(form.id_vin, {'attr': {'style': 'color: white;', 'class': 'form-control'}, 'label_attr': {'style': 'color: white;'}}) }}
    <div class="row g-0 align-items-center">
        <div class="col-6 text-left">
            <button class="btn btn-primary">{{ button_label|default('Sauvegarder') }}</button>
        </div>
        <div class="col-6 text-right">
            <a href="{{ path('app_cave_index') }}" class="btn btn-primary">Page Précédente</a>
        </div>
{{ form_end(form) }}

templates/cave/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Cave{% endblock %}

{% block body %}
    {% include 'homepageTemplate/background.html.twig' %}
    {% include 'homepageTemplate/navBarUtilisateur.html.twig' %}

    <div class="container" style="margin-top:10; margin-left:35%%">
        <div class="row same-height justify-content-center">
            <h1>Modifier votre bouteille</h1>
            {{ include('cave/_form.html.twig') }}
            {{ include('cave/_delete_form.html.twig') }}
        </div>
    </div>
{% endblock %}

templates/cave/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cave index{% endblock %}

{% block body %}
    {% include 'homepageTemplate/background.html.twig' %}
    {% include 'homepageTemplate/navBarUtilisateur.html.twig' %}

    <div class="container" style="margin-top:5%; margin-left:35%%">
        <div class="row same-height justify-content-center text-center">
            <h1>Votre Cave est rempli à {{ remplissage }} %</h1>

            <table class="table-light">
                <thead>
                    <tr>
                        <th>Vin</th>
                        <th>Date d'entré</th>
                        <th>Date de sortie</th>
                        <th>actions</th>
                    </tr>
                </thead>
                <tbody style="top:5%">
                {% for cave in caves %}
                    <tr>
                        <td>{{ cave.nom }}</td>
                        <td>{{ cave.enter_date ? cave.enter_date|date('Y-m-d') : '' }}</td>
                        <td>{{ cave.exit_date ? cave.exit_date|date('Y-m-d') : '' }}</td>
                        <td>
                            <a class="btn btn-primary" href="{{ path('app_cave_edit', {'id': cave.id}) }}">modifier</a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="4">no records found</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            <a  style="margin-top:5%;" class="btn btn-primary" href="{{ path('app_cave_new') }}">Ajouter une bouteille à votre cave</a>
{% endblock %}

templates/cave/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Cave{% endblock %}

{% block body %}
    {% include 'homepageTemplate/background.html.twig' %}
    {% include 'homepageTemplate/navBarUtilisateur.html.twig' %}

    <div class="container" style="margin-top:10; margin-left:35%%">
        <div class="row same-height justify-content-center">
            <h1>Ajouter bouteille à votre cave</h1>
            {{ include('cave/_form.html.twig') }}
        </div>
    </div>
{% endblock %}

templates/cave/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cave{% endblock %}

{% block body %}
    <h1>Cave</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ cave.id }}</td>
            </tr>
            <tr>
                <th>Enter_date</th>
                <td>{{ cave.enterDate ? cave.enterDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Exit_date</th>
                <td>{{ cave.exitDate ? cave.exitDate|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_cave_index') }}">back to list</a>

    <a href="{{ path('app_cave_edit', {'id': cave.id}) }}">edit</a>

    {{ include('cave/_delete_form.html.twig') }}
{% endblock %}